#!/usr/bin/env python3
"""
Aql (العقل) Phase A7.3 — generator for data/nour_knowledge/tutorials.md.

This file is GENERATED FROM src/nour_tutorials.py's TUTORIALS dict,
never hand-maintained -- same "code is the source of truth, docs
follow" discipline as scripts/generate_flag_reference.py (Phase A2.4).

design.md Section 8.3's explicit requirement: the 8 pre-written
tutorials must be retrievable via semantic search, but their text must
NEVER be paraphrased or regenerated by the model -- they are
pre-verified-correct MSA content (grammar-checked once, by a human,
per nour_tutorials.py's own docstring: "NOT AI-generated -- too
important to risk grammar errors"). Generating this file directly from
TUTORIALS (rather than hand-copying the text into a separate .md file)
is what GUARANTEES byte-for-byte verbatim retrieval forever -- there is
no second copy of this content that could ever drift out of sync with
the first.

Usage:
    python3 scripts/generate_tutorials_kb.py
    python3 scripts/generate_tutorials_kb.py --check   # CI-friendly
                                                        # staleness
                                                        # check, no writes

After running (without --check), re-run the embed script for just this
one domain to re-index it:
    python3 scripts/embed_knowledge.py tutorials.md
"""
import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import nour_tutorials  # noqa: E402

OUTPUT_PATH = (Path(__file__).resolve().parent.parent
               / "data" / "nour_knowledge" / "tutorials.md")

HEADER = """# دليل المساعدة السريعة (Tutorials)

> هذا الملف جزء من قاعدة معرفة نور (Aql Phase A7.3، domain: `tutorials`).
>
> **تحذير: هذا الملف مُولَّد تلقائيًّا من `src/nour_tutorials.py`.**
> لا تُعدِّله يدويًّا — أي تعديل يدوي يُفقَد عند إعادة توليد الملف. كل نص
> هنا هو محتوى مُدقَّق بشريًّا مسبقًا (ليس مولَّدًا بالذكاء الاصطناعي) —
> يجب استرجاعه واقتباسه حرفيًّا كما هو، وعدم إعادة صياغته أبدًا (راجع
> design.md Section 8.3). لتحديث المحتوى، غيِّر `TUTORIALS` في
> `src/nour_tutorials.py` ثم أعد تشغيل
> `python3 scripts/generate_tutorials_kb.py`.

"""

# Human-readable Arabic titles per tutorial key, used only as the ##
# heading text -- the BODY under each heading is the exact TUTORIALS
# value, untouched, so retrieval always surfaces the verbatim original.
_TITLES = {
    "recording_mobile": "كيف تسجّل صوتك على الهاتف",
    "wrong_channel": "الأوامر تعمل فقط في قناة مخصصة",
    "done_without_proof": "يجب إنجاز المهمة قبل تسجيلها بأمر تم",
    "streak_broken": "ماذا تفعل عند انقطاع السلسلة",
    "find_tasks": "أين تجد مهامك اليومية",
    "practice_platform_access": "كيف تدخل منصة التمرين",
    "quiz_struggling": "ماذا تفعل عند تكرار الإجابات الخاطئة",
    "first_day_guide": "دليلك ليومك الأول",
}


def generate_markdown() -> str:
    parts = [HEADER]
    for key, content in nour_tutorials.TUTORIALS.items():
        title = _TITLES.get(key, key)
        parts.append(f"## {title}\n\n{content}\n")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true",
                        help="Exit 1 if the existing file is stale, without writing.")
    args = parser.parse_args()

    new_content = generate_markdown()

    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != new_content:
            print(f"STALE: {OUTPUT_PATH} does not match src/nour_tutorials.py. "
                  f"Run without --check to regenerate.", file=sys.stderr)
            return 1
        print(f"OK: {OUTPUT_PATH} is up to date.")
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(new_content, encoding="utf-8")
    print(f"Generated {OUTPUT_PATH} ({len(nour_tutorials.TUTORIALS)} tutorials).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
