"""Nour (نور) — Proactive Outreach Engine.

Reaches out to students BEFORE they ask. The anti-churn system that
makes students feel someone is watching out for them personally.

Runs every 2 hours via discord.ext.tasks loop. Checks for:
1. New students who haven't started (24h after join, 0 tasks)
2. Active students gone quiet (2 days no activity)
3. Score drops (>20% decline over 3 days)
4. First-time milestones (first 7/7 day)

Each message is generated by Groq with the student's specific context,
so it NEVER feels like a template blast.

Note (found during Aql Phase A7.5's audit): flag_registry.py's own
description of `nour_enhanced_proactive` says "9 conditions" and this
docstring previously listed a 5th ("return after absence") that was
never actually implemented in the checks below -- only the 4 checks
above exist in this file today. Documented here rather than silently
"fixed" by inventing a 5th/9th check with no real detection logic
behind it; flag_registry.py's description is corrected in this same
Aql phase to match reality.

Gated behind 'nour_proactive' feature flag.
Rate limit: max 1 proactive DM per student per 6 hours.
"""
import asyncio
import datetime
import logging
import random
from typing import Optional

import aiohttp
import discord

from . import config, database

logger = logging.getLogger("empire-bot.nour.proactive")

# Aql (#15) Phase A7.1: message GENERATION for a detected proactive
# event is redirected through guarded_generate() (design.md Section
# 8.2) -- the DETECTION logic above/below this constant is completely
# UNCHANGED, per that same section's explicit "kept as-is" framing.
# This import is deliberately local-scope inside
# _generate_proactive_message() below, not a module-level import --
# src/nour/guardrails.py imports FROM nour_concierge (for the
# template-fallback list), so a module-level import here risks a
# real circular-import chain (nour_proactive -> nour.guardrails ->
# nour_concierge -> ... ) depending on import order at process
# startup; a local import inside the one function that needs it
# avoids that risk entirely while costing nothing at call time.


# ============================================================
#  OUTREACH LOG (prevent double-sending)
# ============================================================

def _was_outreach_sent(discord_id: str, outreach_type: str, today: str) -> bool:
    """Check if this outreach was already sent today."""
    conn = database._connect()
    row = conn.execute(
        "SELECT id FROM nour_outreach_log WHERE discord_id=? AND outreach_type=? AND date=?",
        (discord_id, outreach_type, today),
    ).fetchone()
    conn.close()
    return row is not None


def _log_outreach(discord_id: str, outreach_type: str, today: str):
    """Record that an outreach was sent."""
    conn = database._connect()
    conn.execute(
        "INSERT INTO nour_outreach_log (discord_id, outreach_type, date) VALUES (?, ?, ?)",
        (discord_id, outreach_type, today),
    )
    conn.commit()
    conn.close()


def _last_outreach_time(discord_id: str) -> Optional[str]:
    """Get the most recent outreach timestamp for rate limiting (6h gap)."""
    conn = database._connect()
    row = conn.execute(
        "SELECT sent_at FROM nour_outreach_log WHERE discord_id=? ORDER BY sent_at DESC LIMIT 1",
        (discord_id,),
    ).fetchone()
    conn.close()
    return row["sent_at"] if row else None


def _is_rate_limited(discord_id: str) -> bool:
    """Check if we've sent a proactive message in the last 6 hours."""
    last = _last_outreach_time(discord_id)
    if not last:
        return False
    try:
        last_dt = datetime.datetime.fromisoformat(last)
        now = datetime.datetime.now()
        return (now - last_dt).total_seconds() < 6 * 3600
    except (ValueError, TypeError):
        return False


# ============================================================
#  MESSAGE GENERATION (Groq — personal, never template-sounding)
# ============================================================

async def _generate_proactive_message(student_name: str, context: str,
                                      outreach_type: str, discord_id: str = "") -> str:
    """Generate a unique proactive message.

    Aql (#15) Phase A7.1: the actual Groq call + this function's own
    per-type fallback strings (used when the API call itself fails --
    missing key, network error, non-200 status) are unchanged from
    before this phase; what's NEW is that the result now passes
    through `guarded_generate()` (design.md Section 8.2) before being
    returned, so a proactive DM gets the exact same script-conformance
    / bidi / role-leak gate every other Nour-generated response gets.
    A guardrail failure here falls back to `guarded_generate()`'s own
    generic template list -- a DIFFERENT, later fallback tier than
    this function's own per-type `fallbacks` dict below, which only
    fires on an outright API failure, not a guardrail failure.
    """
    from .nour.guardrails import guarded_generate
    from .nour.roles import Role

    async def _prompt_fn(correction_hint: Optional[str] = None) -> str:
        return await _call_groq_for_proactive_message(
            student_name, context, outreach_type, correction_hint,
        )

    raw_or_guarded = await guarded_generate(_prompt_fn, role=Role.STUDENT, discord_id=discord_id)
    return raw_or_guarded


async def _call_groq_for_proactive_message(student_name: str, context: str,
                                           outreach_type: str,
                                           correction_hint: Optional[str] = None) -> str:
    """The actual Groq call -- unchanged prompt-construction and
    per-type fallback logic from before Phase A7.1, now callable with
    an optional correction hint appended (guarded_generate()'s retry
    tier, Phase A4)."""
    prompts = {
        "new_student": (
            f"You are Nour, a warm learning coach at Empire English. "
            f"A new student named {student_name} joined 24 hours ago but hasn't started any tasks yet. "
            f"Send them a SHORT warm DM (2-3 sentences, Modern Standard Arabic / فصحى) checking in. "
            f"Be personal, not pushy. Ask if they need help getting started. "
            f"NEVER use Egyptian dialect. Use MSA only. "
            f"Context: {context}"
        ),
        "quiet_student": (
            f"You are Nour, a warm learning coach. "
            f"Student {student_name} hasn't done any tasks for 2 days. "
            f"Send a SHORT warm check-in DM (2-3 sentences, Modern Standard Arabic / فصحى). "
            f"Show you noticed their absence, ask if everything is OK. "
            f"DON'T be guilt-tripping. Be genuinely caring. "
            f"NEVER use Egyptian dialect. Use MSA only. "
            f"Context: {context}"
        ),
        "score_drop": (
            f"You are Nour, a warm learning coach. "
            f"Student {student_name}'s pronunciation scores dropped significantly. "
            f"Send an encouraging DM (2-3 sentences, Modern Standard Arabic / فصحى). "
            f"Acknowledge it's hard, give ONE specific tip, encourage them to keep going. "
            f"NEVER use Egyptian dialect. Use MSA only. "
            f"Context: {context}"
        ),
        "first_milestone": (
            f"You are Nour, a warm learning coach. "
            f"Student {student_name} just completed ALL 7 tasks in one day for the FIRST TIME! "
            f"Send a personal celebration DM (2-3 sentences, Modern Standard Arabic / فصحى). "
            f"Be genuinely excited, mention their specific achievement. "
            f"NEVER use Egyptian dialect. Use MSA only. "
            f"Context: {context}"
        ),
    }

    prompt = prompts.get(outreach_type, prompts["quiet_student"])
    if correction_hint:
        prompt = f"{prompt}\n\n{correction_hint}"

    try:
        url = "https://api.groq.com/openai/v1/chat/completions"
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {config.GROQ_API_KEY}",
        }
        payload = {
            "model": config.GROQ_MODEL,
            "temperature": 0.8,
            "max_tokens": 200,
            "messages": [
                {"role": "system", "content": "أنت نور، مدربة التعلّم في Empire English. تتحدثين بالعربية الفصحى الحديثة. دائمًا ودودة ومشجعة. ردودك قصيرة (2-3 جمل فقط). لا تستخدمي أي لهجة عامية."},
                {"role": "user", "content": prompt},
            ],
        }

        async with aiohttp.ClientSession() as session:
            async with session.post(url, json=payload, headers=headers,
                                    timeout=aiohttp.ClientTimeout(total=15)) as resp:
                if resp.status == 200:
                    data = await resp.json()
                    text = data.get("choices", [{}])[0].get("message", {}).get("content", "")
                    if text:
                        return text.strip().strip('"').strip("'")
    except Exception as e:
        logger.error(f"Proactive message generation failed: {e}")

    # Template fallbacks (never silence)
    fallbacks = {
        "new_student": f"مرحبًا {student_name}! 👋 لاحظت أنك انضممت إلينا بالأمس. هل تحتاج مساعدة للبدء؟ أنا هنا لأي سؤال 😊",
        "quiet_student": f"مرحبًا {student_name}! 👋 هل كل شيء على ما يرام؟ لاحظت أنك لم تدخل مؤخرًا. إذا احتجت أي شيء أنا هنا 💪",
        "score_drop": f"{student_name}، لا بأس إذا شعرت بصعوبة. جميعنا نمر بفترات كهذه. حاول أن تبطئ قليلًا وركّز على كلمة واحدة فقط اليوم 🌟",
        "first_milestone": f"{student_name}! 🎉🎉🎉 أول يوم تُكمل فيه المهام السبع جميعها! هذا إنجاز حقيقي. فخورة بك! 💪🔥",
    }
    return fallbacks.get(outreach_type, fallbacks["quiet_student"])


# ============================================================
#  PROACTIVE CHECKS
# ============================================================

async def run_proactive_checks(bot: discord.Client):
    """Main proactive check — runs every 2 hours.

    Called by the discord.ext.tasks loop in bot.py.
    """
    if not database.is_feature_enabled("nour_proactive"):
        return

    if not config.GROQ_API_KEY:
        return

    guild = bot.get_guild(config.GUILD_ID)
    if not guild:
        return

    # Rawiya R2: also send journey nudges during proactive checks
    from . import nour_journey
    await nour_journey.send_nudges(bot)

    today = datetime.date.today().isoformat()
    now = datetime.datetime.now()
    members = database.all_active_members()
    sent = 0

    for member_data in members:
        discord_id = member_data["discord_id"]

        # Rate limit: max 1 proactive DM per 6 hours
        if _is_rate_limited(discord_id):
            continue

        discord_member = guild.get_member(int(discord_id))
        if not discord_member:
            continue

        name = member_data.get("discord_name", "").split("#")[0] or discord_member.display_name
        outreach_type = None
        context = ""

        # Check 1: New student (joined 24h ago, 0 tasks ever)
        joined = member_data.get("joined_at", "")
        if joined:
            try:
                joined_dt = datetime.datetime.fromisoformat(joined.replace("Z", ""))
                hours_since_join = (now - joined_dt).total_seconds() / 3600
                if 20 <= hours_since_join <= 48:
                    # Joined 20-48h ago — check if they've done anything
                    tasks = database.tasks_completed_today(discord_id)
                    total_submissions = len(database.get_submissions_since(discord_id, 7))
                    if total_submissions == 0:
                        outreach_type = "new_student"
                        context = f"Joined {hours_since_join:.0f}h ago, 0 tasks completed ever"
            except (ValueError, TypeError):
                pass

        # Check 2: Quiet student (2+ days no activity)
        if not outreach_type:
            last_active = member_data.get("last_active_at", "")
            if last_active:
                try:
                    last_dt = datetime.datetime.fromisoformat(last_active.replace("Z", ""))
                    days_inactive = (now - last_dt).days
                    if days_inactive >= 2 and not _was_outreach_sent(discord_id, "quiet_student", today):
                        streak = member_data.get("current_streak", 0)
                        outreach_type = "quiet_student"
                        context = f"Last active {days_inactive} days ago, streak was {streak}"
                except (ValueError, TypeError):
                    pass

        # Check 3: Score drop (>20% decline in 3 days)
        if not outreach_type:
            scores = database.get_recent_scores(discord_id, days=7)
            if len(scores) >= 4:
                recent_2 = [s["score"] for s in scores[:2]]
                older_2 = [s["score"] for s in scores[2:4]]
                if recent_2 and older_2:
                    recent_avg = sum(recent_2) / len(recent_2)
                    older_avg = sum(older_2) / len(older_2)
                    drop = older_avg - recent_avg
                    if drop > 20 and not _was_outreach_sent(discord_id, "score_drop", today):
                        outreach_type = "score_drop"
                        context = f"Score dropped from {older_avg:.0f}% to {recent_avg:.0f}% (−{drop:.0f}%)"

        # Check 4: First 7/7 milestone (just happened today)
        if not outreach_type:
            tasks_today = database.tasks_completed_today(discord_id)
            if len(tasks_today) == 7 and not _was_outreach_sent(discord_id, "first_milestone", today):
                # Check if this is their FIRST ever 7/7 day
                all_time_submissions = database.get_submissions_since(discord_id, 30)
                days_with_7 = {}
                for s in all_time_submissions:
                    d = s.get("date", "")
                    days_with_7[d] = days_with_7.get(d, 0) + 1
                full_days = sum(1 for count in days_with_7.values() if count >= 7)
                if full_days == 1:  # First time ever!
                    outreach_type = "first_milestone"
                    context = f"First ever 7/7 day! Streak: {member_data.get('current_streak', 0)}"

        # Send the outreach if we have one
        if outreach_type:
            message = await _generate_proactive_message(name, context, outreach_type, discord_id=discord_id)
            try:
                await discord_member.send(message)
                _log_outreach(discord_id, outreach_type, today)
                sent += 1
                logger.info(f"Nour proactive: sent '{outreach_type}' to {name}")
            except (discord.Forbidden, discord.HTTPException):
                pass  # DMs disabled or rate limited

            # Don't spam — max 3 outreach messages per check cycle
            if sent >= 3:
                break

            await asyncio.sleep(1)  # Rate limit between sends

    if sent > 0:
        logger.info(f"Nour proactive check complete: {sent} outreach message(s) sent")



# ============================================================
#  RAWIYA R6: GRADUATED PRESENCE
# ============================================================

def get_presence_level(discord_id: str) -> str:
    """Determine how present Nour should be with this student.

    Returns: "high" | "medium" | "low" | "minimal"

    Week 1-2: high (daily presence)
    Week 3-4: medium (every 2-3 days)
    Week 5-8: low (weekly)
    Week 9+:  minimal (monthly + problems only)
    """
    if not database.is_feature_enabled("nour_graduated"):
        return "high"  # Default to high if not enabled

    week = database.member_week_number(discord_id)
    if week <= 2:
        return "high"
    elif week <= 4:
        return "medium"
    elif week <= 8:
        return "low"
    else:
        return "minimal"


def should_send_proactive(discord_id: str, urgency: str = "normal") -> bool:
    """Check if proactive outreach should be sent based on graduated presence.

    urgency: "critical" (always send), "normal" (respect presence level),
             "celebration" (only high/medium)

    Rawiya R6: experienced students aren't over-contacted.
    """
    if not database.is_feature_enabled("nour_graduated"):
        return True  # No graduation, always send

    level = get_presence_level(discord_id)

    if urgency == "critical":
        return True  # Always send critical messages

    if urgency == "celebration":
        return level in ("high", "medium")

    # Normal urgency
    if level == "high":
        return True
    elif level == "medium":
        # Only every 2-3 days: check last outreach
        last = _last_outreach_time(discord_id)
        if not last:
            return True
        try:
            last_dt = datetime.datetime.fromisoformat(last)
            return (datetime.datetime.now() - last_dt).total_seconds() > 2 * 24 * 3600
        except (ValueError, TypeError):
            return True
    elif level == "low":
        # Only weekly
        last = _last_outreach_time(discord_id)
        if not last:
            return True
        try:
            last_dt = datetime.datetime.fromisoformat(last)
            return (datetime.datetime.now() - last_dt).total_seconds() > 7 * 24 * 3600
        except (ValueError, TypeError):
            return True
    else:  # minimal
        # Only monthly (or critical, handled above)
        last = _last_outreach_time(discord_id)
        if not last:
            return True
        try:
            last_dt = datetime.datetime.fromisoformat(last)
            return (datetime.datetime.now() - last_dt).total_seconds() > 30 * 24 * 3600
        except (ValueError, TypeError):
            return True
